import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { apiKey } from '../constants/apikey'
import { generateLocation } from '../components/generateLocation'
import { createContext, useEffect, useState } from 'react'
import { load } from '../storage/storage'

export default function Home() {

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div>
            <ul>
              <li>
                <Link href="#" onClick={generateLocation}>Open Weather App</Link>
              </li>
            </ul>
            <p id="demo"></p>
          </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
